# [![PyPI version](https://img.shields.io/pypi/v/git-fleet-manager.svg)](https://pypi.org/project/git-fleet-manager/)

name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Build package
      run: |
        uv build

    - name: Publish to PyPI
      run: |
        uv publish dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
